mkdir mods
cd mods
echo 'downloading mods...'
curl https://www.curseforge.com/minecraft/mc-mods/jei/download/3040523/file
curl https://www.curseforge.com/minecraft/mc-mods/abyssalcraft/download/3087689/file
curl https://www.curseforge.com/minecraft/mc-mods/baubles/download/2518667/file
curl https://www.curseforge.com/minecraft/mc-mods/thaumcraft/download/2629023/file
curl https://www.curseforge.com/minecraft/mc-mods/thaumic-tinkerer/download/2957213/file
curl https://www.curseforge.com/minecraft/mc-mods/patchouli/download/3162874/file
curl https://www.curseforge.com/minecraft/mc-mods/autoreglib/download/2746011/file
curl https://www.curseforge.com/minecraft/mc-mods/quark/download/2924091/file
curl https://www.curseforge.com/minecraft/mc-mods/botania/download/2846950/file
curl https://www.curseforge.com/minecraft/mc-mods/blood-magic/download/2822288/file
curl https://www.curseforge.com/minecraft/mc-mods/matmos/download/3162960/file
curl https://www.curseforge.com/minecraft/mc-mods/extra-utilities/download/2678374/file
curl https://www.curseforge.com/minecraft/mc-mods/bibliocraft/download/2574880/file
curl https://www.curseforge.com/minecraft/mc-mods/ctm/download/2915363/file
curl https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest/download/3051450/file
curl https://www.curseforge.com/minecraft/mc-mods/headcrumbs/download/2645020/file
curl https://www.curseforge.com/minecraft/mc-mods/openmodslib/download/2699055/file
curl https://www.curseforge.com/minecraft/mc-mods/openblocks/download/2699056/file
curl https://www.curseforge.com/minecraft/mc-mods/iron-chests/download/2747935/file
curl https://www.curseforge.com/minecraft/mc-mods/forge-backpacks/download/2554237/file
curl https://www.curseforge.com/minecraft/mc-mods/fnars-roguelike-dungeons/download/3189628/file
curl https://www.curseforge.com/minecraft/mc-mods/serene-seasons/download/2799213/file
curl https://www.curseforge.com/minecraft/mc-mods/special-mobs/download/2678490/file
curl https://www.curseforge.com/minecraft/mc-mods/ambience-music-mod/download/2491122/file
curl https://www.curseforge.com/minecraft/mc-mods/primitive-mobs/download/2658551/file
curl https://www.curseforge.com/minecraft/mc-mods/primitive-mobs/download/2658551/file
curl https://www.curseforge.com/minecraft/mc-mods/dimensionaldoors/download/2558528/file
curl https://www.curseforge.com/minecraft/mc-mods/chisel/download/2915375/file
curl https://www.curseforge.com/minecraft/mc-mods/astral-sorcery/download/3044416/file
curl https://www.curseforge.com/minecraft/mc-mods/abyssalcraft-integration/download/2959100/file
curl https://www.curseforge.com/minecraft/mc-mods/embers-rekindled/download/3225431/file
curl https://www.curseforge.com/minecraft/mc-mods/mysticallib/download/3243257/file
curl https://www.curseforge.com/minecraft/mc-mods/mystical-world/download/3244451/file
curl https://www.curseforge.com/minecraft/mc-mods/roots/download/3243267/file
curl https://www.curseforge.com/minecraft/mc-mods/thaumic-periphery/download/2766866/file
curl https://www.curseforge.com/minecraft/mc-mods/soot/download/3056967/file
curl https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty/download/2842510/file
curl https://www.curseforge.com/minecraft/mc-mods/multi-mob-core/download/2666556/file
curl https://www.curseforge.com/minecraft/mc-mods/guide-api/download/2645992/file
echo 'all done!'
